"""Skill data models — definitions, metadata, and priority levels.

Represents individual skills that can be loaded from SKILL.md files,
generated by the SkillEvolutionEngine, or registered programmatically.
Supports YAML frontmatter + markdown body format (DeepAgents pattern).
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import Any


class SkillPriority(enum.IntEnum):
    """Priority level determining skill resolution order.

    Lower value = higher priority. Mirrors DeepAgents 7-level hierarchy
    compressed to 4 practical tiers.
    """

    BUILTIN = 10
    PROJECT = 20
    USER = 30
    EVOLVED = 40


@dataclass(frozen=True)
class SkillDefinition:
    """Immutable definition of a single skill.

    Attributes:
        name: Unique machine-readable identifier (e.g. 'damage_inspection').
        description: One-line human summary.
        content: Full skill body (instructions for the LLM).
        allowed_tools: Tool names this skill may invoke. Empty = all.
        tags: Categorization tags for search and filtering.
        priority: Resolution tier (builtin > project > user > evolved).
        version: Monotonic version counter for evolution tracking.
        source_path: File path if loaded from disk, else empty.
        metadata: Arbitrary extra data (owner, trigger, etc.).
    """

    name: str
    description: str
    content: str
    allowed_tools: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    priority: SkillPriority = SkillPriority.USER
    version: int = 1
    source_path: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def tool_restricted(self) -> bool:
        """Whether this skill restricts tool access."""
        return len(self.allowed_tools) > 0

    def matches_tag(self, tag: str) -> bool:
        """Check if skill has a given tag (case-insensitive).

        Args:
            tag: Tag string to match.

        Returns:
            True if the tag is present.
        """
        return tag.lower() in (t.lower() for t in self.tags)

    def to_prompt_block(self) -> str:
        """Format skill as a prompt injection block.

        Returns:
            Markdown-formatted skill block for system prompt.
        """
        tools_line = ""
        if self.allowed_tools:
            tools_line = f"\nAllowed tools: {', '.join(self.allowed_tools)}"

        return (
            f"### Skill: {self.name}\n"
            f"{self.description}\n"
            f"{self.content}"
            f"{tools_line}"
        )

    def to_dict(self) -> dict[str, Any]:
        """Serialize skill to a plain dict.

        Returns:
            Dict representation.
        """
        return {
            "name": self.name,
            "description": self.description,
            "content": self.content,
            "allowed_tools": list(self.allowed_tools),
            "tags": list(self.tags),
            "priority": self.priority.name,
            "version": self.version,
            "source_path": self.source_path,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SkillDefinition:
        """Deserialize from a plain dict.

        Args:
            data: Dict with skill fields.

        Returns:
            SkillDefinition instance.
        """
        priority = _parse_priority(data.get("priority", "USER"))
        return cls(
            name=data.get("name", ""),
            description=data.get("description", ""),
            content=data.get("content", ""),
            allowed_tools=data.get("allowed_tools", []),
            tags=data.get("tags", []),
            priority=priority,
            version=data.get("version", 1),
            source_path=data.get("source_path", ""),
            metadata=data.get("metadata", {}),
        )


def _parse_priority(value: str | int) -> SkillPriority:
    """Parse a priority from string name or int.

    Args:
        value: Priority name or integer value.

    Returns:
        Resolved SkillPriority.
    """
    if isinstance(value, int):
        return SkillPriority(value)
    return SkillPriority[value.upper()]
