"""Value objects for the cross-channel identity graph."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum


__all__ = [
    "ChannelHandle",
    "ChannelKind",
    "GuestIdentity",
    "MatchEvidenceKind",
    "MatchProposal",
]


class ChannelKind(StrEnum):
    """Stable channel taxonomy for handle provenance."""

    AIRBNB = "airbnb"
    BOOKING = "booking"
    VRBO = "vrbo"
    DIRECT = "direct"
    WHATSAPP = "whatsapp"
    SMS = "sms"
    EMAIL = "email"
    PHONE = "phone"


class MatchEvidenceKind(StrEnum):
    """Source of a single match-evidence row."""

    EMAIL_HASH = "email_hash"
    PHONE_HASH = "phone_hash"
    PASSPORT_HASH = "passport_hash"
    BEHAVIOURAL = "behavioural"


@dataclass(frozen=True, slots=True)
class ChannelHandle:
    """One channel-scoped identifier the engine has observed.

    Attributes:
        channel: The channel the identifier was emitted by.
        external_id: The channel's own user / guest id (e.g. an
            Airbnb traveler id).  Free-form string, non-empty.
        email_hash: Optional HMAC-SHA256 hex digest of the
            normalised email address.
        phone_hash: Optional HMAC-SHA256 hex digest of the
            normalised phone number.
        first_seen_at: tz-aware UTC instant the handle was first
            observed; later observations update the canonical
            :class:`GuestIdentity` rather than the handle.
        behavioural_features: Optional set of *behaviour-derived*
            string tokens (writing-style class, booking-timing
            pattern, device family, …) the probabilistic matcher
            uses for Jaccard-similarity merge.  Empty by default;
            populated by the caller from upstream feature
            extraction.
    """

    channel: ChannelKind
    external_id: str
    first_seen_at: datetime
    email_hash: str | None = None
    phone_hash: str | None = None
    behavioural_features: frozenset[str] = frozenset()

    def __post_init__(self) -> None:
        if not self.external_id:
            raise ValueError("external_id required")
        if self.first_seen_at.tzinfo is None:
            raise ValueError("first_seen_at must be tz-aware")
        for name in ("email_hash", "phone_hash"):
            value = getattr(self, name)
            if value is not None and len(value) != 64:
                raise ValueError(
                    f"{name} must be 64 hex chars (HMAC-SHA256)"
                )
        for feature in self.behavioural_features:
            if not isinstance(feature, str) or not feature:
                raise ValueError(
                    "behavioural_features must contain non-"
                    "empty strings"
                )


@dataclass(frozen=True, slots=True)
class GuestIdentity:
    """Canonical record across one or more :class:`ChannelHandle` rows.

    Attributes:
        identity_id: Stable opaque identifier for the canonical
            guest.  Generated by the graph on first observation.
        handles: Tuple of channel handles that resolve to this
            identity.  Order = first-seen order.
        merged_from: When this identity was produced by merging
            two prior identities, the tuple lists their previous
            ``identity_id`` values; empty for fresh identities.
    """

    identity_id: str
    handles: tuple[ChannelHandle, ...]
    merged_from: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.identity_id:
            raise ValueError("identity_id required")
        if not self.handles:
            raise ValueError("handles must be non-empty")


@dataclass(frozen=True, slots=True)
class MatchProposal:
    """Result of a match query.

    Attributes:
        identity_id: The :class:`GuestIdentity` the query resolved
            to (existing or freshly minted).
        kind: Which evidence triggered the resolution.
        confidence: Real number in ``[0.0, 1.0]``; deterministic
            matches return ``1.0``, probabilistic matches return
            the Wilson lower bound on the supporting evidence.
        rationale: One-line plain-English explanation for audit.
        merged: ``True`` when the resolution merged two prior
            identities into one.
    """

    identity_id: str
    kind: MatchEvidenceKind
    confidence: float
    rationale: str
    merged: bool = False
    extra: Mapping[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.identity_id:
            raise ValueError("identity_id required")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                "confidence must be in [0.0, 1.0]"
            )
        if not self.rationale:
            raise ValueError("rationale required")
